# config/config.prod.yaml
app:
  mode: "production"
  port: 80

mysql:
  host: "prod_mysql_host"
  password: "prod_password"

redis:
  host: "prod_redis_host"

elasticsearch:
  addresses: 
    - "http://prod_es_host:9200"