app:
  name: "DistanceBack_v1"
  mode: "development"
  port: 8081
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576

mysql:
  host: "mysql"
  port: 3306
  user: "distance_user"
  password: "distance_password"
  dbname: "distance_back"

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0

firebase:
  credentials_file: "./firebase-credentials.json"
  project_id: "distance-80e4f"           #  project_id
  storage_bucket: "distance-80e4f.firebasestorage.app"  #  storage bucket