# config/config.yaml
app:
  name: "DistanceBack_v1"
  mode: "development"  # development/production
  port: 8080
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576  # 1MB

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "your_password"DistanceBack_v1
  dbname: "distance_back"
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

elasticsearch:
  addresses: 
    - "http://localhost:9200"
  username: ""
  password: ""

firebase:
  credentials_file: "path/to/firebase-credentials.json"
  project_id: "your-project-id"
  storage_bucket: "your-project-id.appspot.com"  # 添加这行