app:
  name: "DistanceBack_v1"
  mode: "development"
  port: 52340
  read_timeout: 60s
  write_timeout: 60s
  max_header_bytes: 1048576

mysql:
  host: "192.168.0.213"
  port: 52342
  user: "distance_user"
  password: "distance_password"
  dbname: "distance_back"

redis:
  host: 192.168.0.213
  port: 52343
  password: "distance_redis_password"
  db: 0

firebase:
  credentials_file: "./firebase-credentials.json"
  project_id: "distance-80e4f"           #  project_id
  storage_bucket: "distance-80e4f.firebasestorage.app"  #  storage bucket